### ISSUE TITLE
Auth link leads to a 404

### ISSUE THREAD

**Issue by almathie** [paylogic/developer.paylogic.com#15]
At the start page of the doc, it is stated that :

Authentication is done via HTTP Basic Auth. All you need is an application id and a secret key, both of which can be obtained from Paylogic.

The paylogic link leads to http://corporate.paylogic.nl/en/contact-information/ which is now a 404.

Additionally, most example in pages such as :

https://doc.sandbox.paylogic.com/events
https://doc.sandbox.paylogic.com/locations
https://doc.sandbox.paylogic.com/products
https://doc.sandbox.paylogic.com/baskets
...

Are just giving : "An Error Occurred"

**Comment by hvdklauw** [comment]
The link was pointing to old documentation, once travis is done building it should be fixed.

Thanks for the report.

**Comment by almathie** [comment]
Thanks !

The update seems live. Just letting you know that as an API consumer :

- In the new doc, you are referring to a username/password HTTP Basic auth. I have a paylogic account as a user (IE : used to buy tickets few weeks/month ago), is it these credentials I am supposed to use ? If not who do I have to ask ? Is it internal use for paylogic employees only ?
- All your example urls are now pointing to shop.paylogic.com, I can't resolve that hostname for my end.

Hartelijk bedankt voor Uw hulp :)

**Comment by hvdklauw** [comment]
If you are serious about selling tickets you can best just send a mail to info@paylogic.nl.

But to do some expectation management: You need to sign a contract with Paylogic before you will get access. This is not a consumer API to programmatically buy tickets for the events you like.
